// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2frucZUuDcVwea6UuDuQZSIQa3gbovEw',
    appId: '1:1094315263303:web:383df6bf6c3226e4347862',
    messagingSenderId: '1094315263303',
    projectId: 'notes-65c34',
    authDomain: 'notes-65c34.firebaseapp.com',
    storageBucket: 'notes-65c34.appspot.com',
    measurementId: 'G-EQ60YVSPNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbhRH_oOINk6rq5U8OJRpB7TSio1Mp3b4',
    appId: '1:1094315263303:android:90a496a61c266181347862',
    messagingSenderId: '1094315263303',
    projectId: 'notes-65c34',
    storageBucket: 'notes-65c34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy0WmCbU43gJwPeP6t_sMnDHMGrN-65v8',
    appId: '1:1094315263303:ios:2445e3942ef1eeb8347862',
    messagingSenderId: '1094315263303',
    projectId: 'notes-65c34',
    storageBucket: 'notes-65c34.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy0WmCbU43gJwPeP6t_sMnDHMGrN-65v8',
    appId: '1:1094315263303:ios:2445e3942ef1eeb8347862',
    messagingSenderId: '1094315263303',
    projectId: 'notes-65c34',
    storageBucket: 'notes-65c34.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2frucZUuDcVwea6UuDuQZSIQa3gbovEw',
    appId: '1:1094315263303:web:e7b1cdf69fbd0214347862',
    messagingSenderId: '1094315263303',
    projectId: 'notes-65c34',
    authDomain: 'notes-65c34.firebaseapp.com',
    storageBucket: 'notes-65c34.appspot.com',
    measurementId: 'G-D46FHGW7T6',
  );

}